/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/accueil` | `/accueil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/message` | `/message`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rechercher` | `/rechercher`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vendre` | `/vendre`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/accueil` | `/accueil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/message` | `/message`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/rechercher` | `/rechercher`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/vendre` | `/vendre`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/accueil${`?${string}` | `#${string}` | ''}` | `/accueil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/message${`?${string}` | `#${string}` | ''}` | `/message${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profil${`?${string}` | `#${string}` | ''}` | `/profil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/rechercher${`?${string}` | `#${string}` | ''}` | `/rechercher${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/vendre${`?${string}` | `#${string}` | ''}` | `/vendre${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/accueil` | `/accueil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/message` | `/message`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rechercher` | `/rechercher`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vendre` | `/vendre`; params?: Router.UnknownInputParams; };
    }
  }
}
